(WIP) Use the `vm` module of Node.js for evaluation.
I got a problem that `importModuleDynamically` doesn't work with test-assets/a.js while work well with src/lib/meta.ts.

`import`ting test-assets/a.js fails with this error:

```javascript
Error: Provided module is not an instance of Module
 ❯ async Module.evalBlock src/eval.ts:44:9
     42|
     43|   console.log(jsSrc);
     44|   return await vm.runInContext(jsSrc, env.o.vmContext, createVmOptions(env.o));
       |         ^
     45| }
     46|
```

I guess this is related to Vite's interception: `import`ting meta.ts succeeds thanks to Vite's transformation of `import()`, but `import`ing a.js isn't transformed. So I suspect just calling the original `import` function doesn't work in `importModuleDynamically`.

But I failed to confirm the hypothesis above by running raw Node this script:

```javascript
import * as vm from 'node:vm';

const context = {};
vm.createContext(context);
const f = () => {
  return vm.runInContext(
  "import('./test-assets/a.js').then((a) => { console.log('a.a', a.a) });",
  context,
  {
    importModuleDynamically: async (specifier) => await import(specifier)),
  }
)
};
f();
```

This script calls the raw `import` function, so this script should fail with the same error I showed before, but successfully runs.

Anyway, it might be better to give up using vitest for the testing framework of this project.